version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3305:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin3000

volumes:
  my-db:
  minio_data:
    driver: local